import {
  ScrollView,
  Text,
  View,
  TouchableOpacity,
  TextInput,
  Alert,
  Share,
  Platform,
} from "react-native";
import { useRouter, useLocalSearchParams } from "expo-router";
import { useState, useEffect } from "react";
import * as Haptics from "expo-haptics";

import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { Session, SessionType, Finding, SOAPNote } from "@/types/session";
import { saveSession, getSession } from "@/lib/session-storage";
import { generateSOAPNote, formatSessionDate, formatSessionTime } from "@/lib/soap-generator";

export default function SessionReviewScreen() {
  const router = useRouter();
  const colors = useColors();
  const params = useLocalSearchParams();

  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<Session | null>(null);
  const [soapNote, setSoapNote] = useState<SOAPNote>({
    subjective: "",
    objective: "",
    assessment: "",
    plan: "",
  });
  const [editingSection, setEditingSection] = useState<keyof SOAPNote | null>(null);

  useEffect(() => {
    loadSession();
  }, []);

  const loadSession = async () => {
    try {
      const isNew = params.isNew === "true";

      if (isNew) {
        // Create new session from params
        const newSession: Session = {
          id: params.sessionId as string,
          clientName: params.clientName as string,
          sessionType: params.sessionType as SessionType,
          status: "completed",
          startTime: new Date(),
          endTime: new Date(),
          duration: parseInt(params.duration as string, 10),
          findings: [], // In real implementation, pass findings from active session
          soapNote: {
            subjective: "",
            objective: "",
            assessment: "",
            plan: "",
          },
          notes: params.notes as string | undefined,
        };

        // Generate SOAP note
        const generatedNote = generateSOAPNote(
          newSession.findings,
          newSession.sessionType,
          newSession.clientName
        );

        newSession.soapNote = generatedNote;
        setSoapNote(generatedNote);
        setSession(newSession);
      } else {
        // Load existing session
        const existingSession = await getSession(params.id as string);
        if (existingSession) {
          setSession(existingSession);
          setSoapNote(existingSession.soapNote);
        } else {
          Alert.alert("Error", "Session not found.");
          router.back();
        }
      }
    } catch (error) {
      console.error("Error loading session:", error);
      Alert.alert("Error", "Failed to load session.");
      router.back();
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!session) return;

    if (Platform.OS !== "web") {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }

    try {
      const updatedSession = {
        ...session,
        soapNote,
      };

      await saveSession(updatedSession);
      Alert.alert("Success", "Session saved successfully.", [
        {
          text: "OK",
          onPress: () => router.push("/(tabs)/" as any),
        },
      ]);
    } catch (error) {
      console.error("Error saving session:", error);
      Alert.alert("Error", "Failed to save session.");
    }
  };

  const handleExport = async () => {
    if (!session) return;

    if (Platform.OS !== "web") {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }

    const exportText = `
SOAP NOTE
=========

Client: ${session.clientName}
Date: ${formatSessionDate(session.startTime)} ${formatSessionTime(session.startTime)}
Session Type: ${session.sessionType}
Duration: ${Math.floor(session.duration / 60)} minutes

SUBJECTIVE
----------
${soapNote.subjective}

OBJECTIVE
---------
${soapNote.objective}

ASSESSMENT
----------
${soapNote.assessment}

PLAN
----
${soapNote.plan}

---
Generated by SomaSync AI
    `.trim();

    try {
      await Share.share({
        message: exportText,
        title: `SOAP Note - ${session.clientName}`,
      });
    } catch (error) {
      console.error("Error sharing:", error);
    }
  };

  const handleEditSection = (section: keyof SOAPNote) => {
    if (Platform.OS !== "web") {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }
    setEditingSection(section);
  };

  const handleSaveSection = () => {
    if (Platform.OS !== "web") {
      Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);
    }
    setEditingSection(null);
  };

  const SOAPSection = ({
    title,
    section,
    content,
  }: {
    title: string;
    section: keyof SOAPNote;
    content: string;
  }) => {
    const isEditing = editingSection === section;

    return (
      <View className="bg-surface rounded-xl p-4 border border-border gap-3">
        <View className="flex-row justify-between items-center">
          <Text className="text-lg font-bold text-foreground">{title}</Text>
          <TouchableOpacity
            onPress={() => (isEditing ? handleSaveSection() : handleEditSection(section))}
            activeOpacity={0.7}
          >
            <IconSymbol
              name={isEditing ? "checkmark.circle.fill" : "pencil"}
              size={20}
              color={isEditing ? colors.success : colors.primary}
            />
          </TouchableOpacity>
        </View>

        {isEditing ? (
          <TextInput
            value={content}
            onChangeText={(text) => setSoapNote((prev) => ({ ...prev, [section]: text }))}
            multiline
            numberOfLines={6}
            textAlignVertical="top"
            className="bg-background rounded-lg px-3 py-2 text-base text-foreground border border-border"
          />
        ) : (
          <Text className="text-base text-foreground leading-relaxed">{content}</Text>
        )}
      </View>
    );
  };

  if (loading) {
    return (
      <ScreenContainer className="p-6">
        <View className="flex-1 items-center justify-center">
          <Text className="text-muted">Loading session...</Text>
        </View>
      </ScreenContainer>
    );
  }

  if (!session) {
    return null;
  }

  return (
    <ScreenContainer className="p-6">
      <ScrollView contentContainerStyle={{ paddingBottom: 32 }}>
        <View className="gap-6">
          {/* Header */}
          <View className="gap-2">
            <Text className="text-3xl font-bold text-foreground">Session Review</Text>
            <Text className="text-base text-muted">
              Review and edit your AI-generated SOAP note
            </Text>
          </View>

          {/* Session Info */}
          <View className="bg-surface rounded-xl p-4 border border-border gap-2">
            <Text className="text-xl font-semibold text-foreground">{session.clientName}</Text>
            <Text className="text-sm text-muted">
              {formatSessionDate(session.startTime)} • {Math.floor(session.duration / 60)} minutes
            </Text>
            <Text className="text-sm text-muted capitalize">
              {session.sessionType.replace("_", " ")} Session
            </Text>
          </View>

          {/* SOAP Note Sections */}
          <SOAPSection title="Subjective" section="subjective" content={soapNote.subjective} />
          <SOAPSection title="Objective" section="objective" content={soapNote.objective} />
          <SOAPSection title="Assessment" section="assessment" content={soapNote.assessment} />
          <SOAPSection title="Plan" section="plan" content={soapNote.plan} />

          {/* Action Buttons */}
          <View className="gap-3 mt-4">
            <TouchableOpacity
              onPress={handleSave}
              activeOpacity={0.9}
              className="bg-primary rounded-2xl py-4 items-center flex-row justify-center gap-2"
            >
              <IconSymbol name="checkmark.circle.fill" size={24} color="#FFFFFF" />
              <Text className="text-lg font-bold text-white">Save Session</Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={handleExport}
              activeOpacity={0.7}
              className="bg-surface rounded-2xl py-4 items-center flex-row justify-center gap-2 border border-border"
            >
              <IconSymbol name="square.and.arrow.up" size={20} color={colors.foreground} />
              <Text className="text-base font-semibold text-foreground">Export / Share</Text>
            </TouchableOpacity>

            <TouchableOpacity
              onPress={() => router.back()}
              activeOpacity={0.7}
              className="py-3 items-center"
            >
              <Text className="text-base text-muted">Cancel</Text>
            </TouchableOpacity>
          </View>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
